### ISSUE TITLE
TransformError react native0.63.2

### ISSUE THREAD

**Issue by zaleer** [oblador/react-native-animatable#326]
react native: 0.63.2

Error: {"type":"TransformError","lineNumber":0,"errors":[{"description":"node_modules/react-native-animatable/index.js: Cannot find module '/Users/zale/Documents/project_work/components/react-native-jy-tools/example/node_modules/@react-native-community/cli/node_modules/metro-react-native-babel-transformer/src/index.js'","lineNumber":0}],

**Comment by Santix11** [comment]
Im facing a similar issue on RN 0.74.3. I have 2 projects with the same RN version and almost identical dependencies. However, one of the projects throws this error but the other does not. It only happens when I use react-native-modal even though this package works fine on my other project.

error: node_modules/react-native-animatable/createAnimatableComponent.js: react-native-project/node_modules/react-native-animatable/createAnimatableComponent.js: path.requeueComputedKeyAndDecorators is not a function

**Comment by nikunjdhamelia** [comment]
I am encountering the same issue with RN 0.74.5 version.

error: node_modules/react-native-modal/node_modules/react-native-animatable/createAnimatableComponent.js: /Users/nikunj/Documents/React-Native/Njoy/node_modules/react-native-modal/node_modules/react-native-animatable/createAnimatableComponent.js: path.requeueComputedKeyAndDecorators is not a function
